/*Work in progress, will be simplified*/ let q = null; function y(g, i, d) { function f(b, h, e, a, d, f) { var j = c(); if (j) { typeof f === "undefined" && (f = !0); if (h) typeof j.onload != "undefined" ? j.onload = ()=>{ j.status == "200" || j.status == "206" ? (j.fileSize = d || j.getResponseHeader("Content-Length"), h(j)) : e && e(); j = q } : j.onreadystatechange = ()=>{ if (j.readyState == 4) j.status == "200" || j.status == "206" ? (j.fileSize = d || j.getResponseHeader("Content-Length"), h(j)) : e && e(), j = q }; j.open("GET", b, f); j.overrideMimeType && j.overrideMimeType("text/plain; charset=x-user-defined"); a && j.setRequestHeader("Range", "bytes=" + a[0] + "-" + a[1]); j.setRequestHeader("If-Modified-Since", "Sat, 1 Jan 1970 00:00:00 GMT"); j.send(q) } else e && e() } function c() { var b = q; if (window.XMLHttpRequest) b = new XMLHttpRequest; return b } function a(b, h) { var e = c(); if (e) { if (h) typeof e.onload != "undefined" ? e.onload = ()=>{ e.status == "200" && h(this); e = q } : e.onreadystatechange = ()=>{ e.readyState == 4 && (e.status == "200" && h(this), e = q) }; e.open("HEAD", b, !0); e.send(q) } } function b(b, h) { var e, a; function c(b) { var p = ~~(b[0] / e) - a, b = ~~(b[1] / e) + 1 + a; p < 0 && (p = 0); b >= blockTotal && (b = blockTotal - 1); return [p, b] } function g(a, c) { for (; n[a[0]];)if (a[0]++ , a[0] > a[1]) { c && c(); return } for (; n[a[1]];)if (a[1]-- , a[0] > a[1]) { c && c(); return } var k = [a[0] * e, (a[1] + 1) * e - 1]; f(b, (b)=>{ parseInt(b.getResponseHeader("Content-Length"), 10) == h && (a[0] = 0, a[1] = blockTotal - 1, k[0] = 0, k[1] = h - 1); for (var b = { data: b.W || b.responseText, s: k[0] }, p = a[0]; p <= a[1]; p++)n[p] = b; i += k[1] - k[0] + 1; c && c() }, d, k, j, !!c) } var j, i = 0, l = new z("", 0, h), n = []; e = e || 2048; a = typeof a === "undefined" ? 0 : a; blockTotal = ~~((h - 1) / e) + 1; for (var m in l) l.hasOwnProperty(m) && typeof l[m] === "function" && (this[m] = l[m]); this.a =(b)=>{ var a; g(c([b, b])); a = n[~~(b / e)]; if (typeof a.data == "string") return a.data.charCodeAt(b - a.s) & 255 }; this.N = ()=>{ return i }; this.f =(b,a)=>{ g(c(b), a) } } (()=>{ a(g, (a)=>{ a = parseInt(a.getResponseHeader("Content-Length"), 10) || -1; i(new b(g, a)) }) })() }
function z(g, i, d) {
    var f = g, c = i || 0, a = 0; this.P = ()=>{ return f }; if (typeof g == "string") a = d || f.length, this.a = function (b) { return f.charCodeAt(b + c) & 255 }; this.n = function (b, a) { for (var h = Array(a), e = 0; e < a; e++)h[e] = this.a(b + e); return h }; this.j = ()=>{ return a }; this.d = function (b, a) { return (this.a(b) & 1 << a) != 0 }; this.Q = function (b) { b = this.a(b); return b > 127 ? b - 256 : b }; this.r = function (b, a) {
        var h = a ? (this.a(b) <<
            8) + this.a(b + 1) : (this.a(b + 1) << 8) + this.a(b); h < 0 && (h += 65536); return h
    }; this.S = function (b, a) { var h = this.r(b, a); return h > 32767 ? h - 65536 : h }; this.h = function (b, a) { var h = this.a(b), e = this.a(b + 1), c = this.a(b + 2), d = this.a(b + 3), h = a ? (((h << 8) + e << 8) + c << 8) + d : (((d << 8) + c << 8) + e << 8) + h; h < 0 && (h += 4294967296); return h }; this.R = function (b, a) { var c = this.h(b, a); return c > 2147483647 ? c - 4294967296 : c }; this.q = function (b) { var a = this.a(b), c = this.a(b + 1), b = this.a(b + 2), a = ((a << 8) + c << 8) + b; a < 0 && (a += 16777216); return a }; this.c = function (b, a) {
        for (var c =
            [], e = b, d = 0; e < b + a; e++ , d++)c[d] = String.fromCharCode(this.a(e)); return c.join("")
    }; this.e = function (b, a, c) {
        b = this.n(b, a); switch (c.toLowerCase()) {
            case "utf-16": case "utf-16le": case "utf-16be": var a = c, e, d = 0, f = 1, c = 0; e = Math.min(e || b.length, b.length); b[0] == 254 && b[1] == 255 ? (a = !0, d = 2) : b[0] == 255 && b[1] == 254 && (a = !1, d = 2); a && (f = 0, c = 1); for (var a = [], g = 0; d < e; g++) { var j = b[d + f], i = (j << 8) + b[d + c]; d += 2; if (i == 0) break; else j < 216 || j >= 224 ? a[g] = String.fromCharCode(i) : (j = (b[d + f] << 8) + b[d + c], d += 2, a[g] = String.fromCharCode(i, j)) } b =
                new String(a.join("")); b.g = d; break; case "utf-8": e = 0; d = Math.min(d || b.length, b.length); b[0] == 239 && b[1] == 187 && b[2] == 191 && (e = 3); f = []; for (c = 0; e < d; c++)if (a = b[e++], a == 0) break; else a < 128 ? f[c] = String.fromCharCode(a) : a >= 194 && a < 224 ? (g = b[e++], f[c] = String.fromCharCode(((a & 31) << 6) + (g & 63))) : a >= 224 && a < 240 ? (g = b[e++], i = b[e++], f[c] = String.fromCharCode(((a & 255) << 12) + ((g & 63) << 6) + (i & 63))) : a >= 240 && a < 245 && (g = b[e++], i = b[e++], j = b[e++], a = ((a & 7) << 18) + ((g & 63) << 12) + ((i & 63) << 6) + (j & 63) - 65536, f[c] = String.fromCharCode((a >> 10) + 55296,
                    (a & 1023) + 56320)); b = new String(f.join("")); b.g = e; break; default: d = []; f = f || b.length; for (e = 0; e < f;) { c = b[e++]; if (c == 0) break; d[e - 1] = String.fromCharCode(c) } b = new String(d.join("")); b.g = e
        }return b
    }; this.M = (a)=>{ return String.fromCharCode(this.a(a)) }; this.Z = ()=>{ return window.btoa(f) }; this.L = (a)=>{ f = window.atob(a) }; this.f = (a,c)=>{ c() }
}

(function (g) { g.FileAPIReader = function (g) { return function (d, f) { var c = new FileReader; c.onload = (a)=>{ f(new z(a.target.result)) }; c.readAsBinaryString(g) } } })(this); (function (g) { g.k = { i: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=", z: function (g) { for (var d = "", f, c, a, b, p, h, e = 0; e < g.length;)f = g[e++], c = g[e++], a = g[e++], b = f >> 2, f = (f & 3) << 4 | c >> 4, p = (c & 15) << 2 | a >> 6, h = a & 63, isNaN(c) ? p = h = 64 : isNaN(a) && (h = 64), d = d + Base64.i.charAt(b) + Base64.i.charAt(f) + Base64.i.charAt(p) + Base64.i.charAt(h); return d } }; g.Base64 = g.k; g.k.encodeBytes = g.k.z })(this); (function (g) {
    var i = g.t = {}, d = {}, f = [0, 7]; i.C = function (c, a, b) { b = b || {}; (b.dataReader || y)(c, function (g) { g.f(f, ()=>{ var f = g.c(4, 7) == "ftypM4A" ? ID4 : g.c(0, 3) == "ID3" ? ID3v2 : ID3v1; f.o(g, ()=>{ var e = b.tags, i = f.p(g, e), e = d[c] || {}, k; for (k in i) i.hasOwnProperty(k) && (e[k] = i[k]); d[c] = e; a && a() }) }) }) }; i.A = function (c) { if (!d[c]) return q; var a = {}, b; for (b in d[c]) d[c].hasOwnProperty(b) && (a[b] = d[c][b]); return a }; i.B = function (c, a) { if (!d[c]) return q; return d[c][a] }; g.ID3 = g.t; i.loadTags = i.C; i.getAllTags = i.A; i.getTag =
        i.B
})(this); ((g)=>{
    var i = g.u = {}, d = ['']; i.o =(d, c)=>{ var a = d.j(); d.f([a - 128 - 1, a], c) }; i.p =(f)=>{
            var c = f.j() - 128; if (f.c(c, 3) == "TAG") {
                var a = f.c(c + 3, 30).replace(/\0/g, ""), b = f.c(c + 33, 30).replace(/\0/g, ""), g = f.c(c + 63, 30).replace(/\0/g, ""), h = f.c(c + 93, 4).replace(/\0/g, ""); if (f.a(c + 97 + 28) == 0) var e = f.c(c + 97, 28).replace(/\0/g, ""), i = f.a(c + 97 + 29); else e = "", i = 0; f = f.a(c + 97 + 30); return { version: "1.1", title: a, artist: b, album: g }
            } else return {}
        }; g.ID3v1 = g.u
})(this); (function (g) {
    function i(a, b) { var c = b.a(a), d = b.a(a + 1), e = b.a(a + 2); return b.a(a + 3) & 127 | (e & 127) << 7 | (d & 127) << 14 | (c & 127) << 21 } var d = g.G = {}; d.b = {}; d.frames = {
        PIC: "Picture", TAL: "Album", TP1: "Artist", TT2: "Title", APIC: "Picture", TALB: "Album", TIT2: "Title", TPE1: "Artist" }; var f = { title: ["TIT2", "TT2"], artist: ["TPE1", "TP1"], album: ["TALB", "TAL"], picture: ["APIC", "PIC"] }, c = ["title", "artist", "album"]; d.o = (a,b)=>{ a.f([0, i(6, a)], b) }; d.p = (a,b)=>{
        var g = 0, h = a.a(g + 3); if (h > 4) return { version: ">2.4" }; var e = a.a(g + 4), v = a.d(g + 5, 7), k = a.d(g + 5, 6), s = a.d(g + 5, 5), j = i(g + 6, a); g += 10; if (k) { var o = a.h(g, !0); g += o + 4 } var h = {
            version: "2." + h + "." + e, major: h, revision: e, flags: { unsynchronisation: v, extended_header: k, experimental_indicator: s },
            size: j
        }, l; if (v) l = {}; else {
            j -= 10; for (var v = a, e = b, k = {}, s = h.major, o = [], n = 0, m; m = (e || c)[n]; n++)o = o.concat(f[m] || [m]); for (e = o; g < j;) {
                o = q; n = v; m = g; var u = q; switch (s) { case 2: l = n.c(m, 3); var r = n.q(m + 3), t = 6; break; case 3: l = n.c(m, 4); r = n.h(m + 4, !0); t = 10; break; case 4: l = n.c(m, 4), r = i(m + 4, n), t = 10 }if (l == "") break; g += t + r; if (!(e.indexOf(l) < 0) && (s > 2 && (u = { message: { Y: n.d(m + 8, 6), K: n.d(m + 8, 5), V: n.d(m + 8, 4) }, m: { T: n.d(m + 8 + 1, 7), H: n.d(m + 8 + 1, 3), J: n.d(m + 8 + 1, 2), D: n.d(m + 8 + 1, 1), w: n.d(m + 8 + 1, 0) } }), m += t, u && u.m.w && (i(m, n), m += 4, r -= 4), !u || !u.m.D)) l in
                    d.b ? o = d.b[l] : l[0] == "T" && (o = d.b["T*"]), o = o ? o(m, r, n, u) : void 0, o = { id: l, size: r, description: l in d.frames ? d.frames[l] : "Unknown", data: o }, l in k ? (k[l].id && (k[l] = [k[l]]), k[l].push(o)) : k[l] = o
            } l = k
        } for (var w in f) if (f.hasOwnProperty(w)) { a: { r = f[w]; typeof r == "string" && (r = [r]); t = 0; for (g = void 0; g = r[t]; t++)if (g in l) { a = l[g].data; break a } a = void 0 } a && (h[w] = a) } for (var x in l) l.hasOwnProperty(x) && (h[x] = l[x]); return h
    }; g.ID3v2 = d
})(this); (()=>{
    function g(d) { var f; switch (d) { case 0: f = "iso-8859-1"; break; case 1: f = "utf-16"; break; case 2: f = "utf-16be"; break; case 3: f = "utf-8" }return f } var i = ["32x32 pixels 'file icon' (PNG only)", "Other file icon", "Cover (front)", "Cover (back)", "Leafvar page", "Media (e.g. lable side of CD)", "Lead artist/lead performer/soloist", "Artist/performer", "Conductor", "Band/Orchestra", "Composer", "Lyricist/text writer", "Recording Location", "During recording", "During performance", "Movie/video screen capture", "A bright coloured fish", "Illustration", "Band/artist logotype", "Publisher/Studio logotype"]; ID3v2.b.APIC = function (d, f, c, a, b) { var b = b || "3", a = d, p = g(c.a(d)); switch (b) { case "2": var h = c.c(d + 1, 3); d += 4; break; case "3": case "4": h = c.e(d + 1, f - (d - a), p), d += 1 + h.g }b = c.a(d, 1); b = i[b]; p = c.e(d + 1, f - (d - a), p); d += 1 + p.g; return { format: h.toString(), type: b, description: p.toString(), data: c.n(d, a + f - d) } }; ID3v2.b.PIC = function (d, f, c, a) { return ID3v2.b.APIC(d, f, c, a, "2") }; ID3v2.b["T*"] = function (d, f, c) { var a = g(c.a(d)); return c.e(d + 1, f - 1, a).toString() };
})(); (function (g) {
    function i(c, a, b, d) { var g = c.h(a, !0); if (g == 0) d(); else { var e = c.c(a + 4, 4);["moov", "udta", "meta", "ilst"].indexOf(e) > -1 ? (e == "meta" && (a += 4), c.f([a + 8, a + 8 + 8], ()=>{ i(c, a + 8, g - 8, d) })) : c.f([a + (e in f.l ? 0 : g), a + g + 8], ()=>{ i(c, a + g, b, d) }) } } function d(c, a, b, g, h) {
        for (var h = h === void 0 ? "" : h + "  ", e = b; e < b + g;) {
            var i = a.h(e, !0); if (i == 0) break; var k = a.c(e + 4, 4); if (["moov", "udta", "meta", "ilst"].indexOf(k) > -1) { k == "meta" && (e += 4); d(c, a, e + 8, i - 8, h); break } if (f.l[k]) {
                var s = a.q(e + 16 + 1), j = f.l[k], s = f.types[s]; if (k ==
                    "trkn") c[j[0]] = a.a(e + 16 + 11), c.count = a.a(e + 16 + 13); else { var k = e + 16 + 4 + 4, o = i - 16 - 4 - 4; switch (s) { case "text": c[j[0]] = a.e(k, o, "UTF-8"); break; case "uint8": c[j[0]] = a.r(k); break; case "jpeg": case "png": c[j[0]] = { m: "image/" + s, data: a.n(k, o) } } }
            } e += i
        }
    } var f = g.v = {}; f.types = { 0: "uint8", 1: "text", 13: "jpeg", 14: "png", 21: "uint8" }; f.l = { "\u00a9alb": ["album"], "\u00a9art": ["artist"], "\u00a9ART": ["artist"], aART: ["artist"], "\u00a9nam": ["title"], covr: ["picture"] };
    f.o = function (c, a) { c.f([0, 7], ()=>{ i(c, 0, c.j(), a) }) }; f.p = function (c) { var a = {}; d(a, c, 0, c.j()); return a }; g.ID4 = g.v
})(this);
